module.exports = [
    "What flaw in other people do you find most forgivable?",
    "How close do you think you are to people's images of you? Do people often get the wrong impression of you?",
    "Could you keep living indefinitely the way you are living now?",
    "Are you ever inexplicably happy?",
    "Name a good part of your life that is gone now, and probably won't ever come back.",
    "Are you ever inexplicably sad?",
    "If you could live in any culture in the world, from any time period, from any place, where would it be?",
    "Would you rather be a child or an adult?",
    "If you could have a superpower, what would you choose?",
    "What is your idea of misery?",
    "What is something that you can do without thinking about it?",
    "What is your idea of happiness?",
    "When you are angry, what can people do to make you feel better?",
    "How do you express yourself when you've been hurt?",
    "What kind of compliments make you feel proud?",
    "How much pressure are you under right now? too much? not enough? how does that feel?",
    "What is something you have always wanted to do?",
    "How much time do you spend preparing for life in ratio to the time you spend living? Is it too much or not enough?"
];